# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The length is no more than 100 characters.', max_length=100, verbose_name='Country Name')),
                ('iso_code_3', models.CharField(help_text='The length is no more than 3 characters.', max_length=3, verbose_name='Country ISO Code')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Disable'), (1, 'Enable')], default=0, verbose_name='Status')),
            ],
            options={
                'db_table': 'test_country',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The length is no more than 100 characters.', max_length=100, verbose_name='Zone Name')),
                ('code', models.CharField(help_text='The length is no more than 3 characters.', max_length=3, verbose_name='Zone Code')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Disable'), (1, 'Enable')], default=0, verbose_name='Status')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localisation.Country')),
            ],
            options={
                'db_table': 'test_zone',
            },
        ),
    ]
