# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Localisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zone', 'verbose_name_plural': 'Zone'},
        ),
    ]
