# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 15:34
from __future__ import unicode_literals

import TestUsePostgreSQL.apps.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_auto_20170310_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(help_text='For Example: 6261234567.', max_length=20, validators=[TestUsePostgreSQL.apps.validation.validator_number]),
        ),
        migrations.AlterField(
            model_name='authoraddress',
            name='address_1',
            field=models.CharField(help_text='This length is no more than 50 characters.', max_length=50, validators=[TestUsePostgreSQL.apps.validation.validator_special_character]),
        ),
        migrations.AlterField(
            model_name='authoraddress',
            name='address_2',
            field=models.CharField(blank=True, help_text='Apt. No., Suite No. and so on. This length is no more than 50 characters.', max_length=50, validators=[TestUsePostgreSQL.apps.validation.validator_special_character]),
        ),
        migrations.AlterField(
            model_name='authoraddress',
            name='zip',
            field=models.CharField(help_text='Zipcode. This length is no more than 20 characters.', max_length=20, validators=[TestUsePostgreSQL.apps.validation.validator_number]),
        ),
    ]
