# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The length is no more than 100 characters.', max_length=100)),
                ('summary', models.TextField(blank=True, help_text='The length is no more than 300 characters.', max_length=300)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Arrived'), (10, 'New Book For Sale'), (15, 'For Sale'), (20, 'Discount'), (30, 'Discontinued'), (40, 'Special Offer'), (50, 'Sold Out')], default=0)),
                ('publish_date', models.DateField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('author', models.ManyToManyField(to='Author.Author')),
            ],
            options={
                'db_table': 'test_book',
            },
        ),
    ]
