# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0001_initial'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Publisher.Publisher'),
            preserve_default=False,
        ),
    ]
