# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20170314_2135'),
        ('Book', '0004_auto_20170315_1534'),
    ]

    operations = [
    ]
